/**
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.11.1/userguide/building_java_projects.html in the Gradle documentation.
 */
plugins {
    java
    application
    id("com.gradleup.shadow") version "9.0.0-beta7"
    jacoco

    id("org.danilopianini.unibo-oop-gradle-plugin") version "1.0.14-dev0o-a764058"
}

java { toolchain { languageVersion.set(JavaLanguageVersion.of(17)) } }


repositories {
    mavenCentral()
}

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.1")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    testImplementation("org.mockito:mockito-core:3.+")

    implementation("com.google.guava:guava:32.1.2-jre")
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

application {
    mainClass.set("it.unibo.Main")
}

tasks.test {
    useJUnitPlatform()
}

buildscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath("com.gradleup.shadow:shadow-gradle-plugin:9.0.0-beta7")
    }
}

apply(plugin = "java")
apply(plugin = "com.gradleup.shadow")
