/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.11.1/userguide/building_java_projects.html in the Gradle documentation.
 */
plugins {
    // Plugin per il progetto Java e l'applicazione
    java
    application
    id("com.gradleup.shadow") version "9.0.0-beta7"
}

repositories {
    // Usa Maven Central per risolvere le dipendenze
    mavenCentral()
}

dependencies {
    // JUnit 5: Aggiungi la libreria completa
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.1")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // Dipendenze dell'applicazione
    implementation("com.google.guava:guava:32.1.2-jre") // Usa una versione specifica
}

// Configura la versione di Java
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

application {
    // Specifica la classe principale
    mainClass.set("it.unibo.Main")
}

// Abilita JUnit 5 nei test
tasks.test {
    useJUnitPlatform()
}

// Configurazione del plugin shadowJar per creare un JAR eseguibile
buildscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath("com.gradleup.shadow:shadow-gradle-plugin:9.0.0-beta7")
    }
}

apply(plugin = "java")
apply(plugin = "com.gradleup.shadow")
