/*
 * This source file was generated by the Gradle 'init' task
 */
package it.unibo;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void axiom() {
        assertTrue(true);
    }
}
