/*
 * This source file was generated by the Gradle 'init' task
 */
package it.unibo;

import javafx.scene.Scene;
import javafx.scene.Group;
import javafx.stage.Stage;

public class App extends javafx.application.Application {
    @Override
    public void start(Stage stage) throws Exception {
        Group root = new Group();
        Scene scene = new Scene(root, 500, 300);
        stage.setTitle("Puyo Pop Blast!");
        stage.setScene(scene);
        stage.show();
    }
}